const ADD_USER_INFO_LOADING = 'ADD_USER_INFO_LOADING';
const ADD_USER_INFO_SUCCESS = 'ADD_USER_INFO_SUCCESS';
const ADD_USER_INFO_FAILURE = 'ADD_USER_INFO_FAILURE';


const GET_USER_INFO_LOADING = 'GET_USER_INFO_LOADING';
const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

const USER_LOGOUT = 'USER_LOGOUT';


export const userActionType = {
    ADD_USER_INFO_LOADING,
    ADD_USER_INFO_SUCCESS,
    ADD_USER_INFO_FAILURE,
    GET_USER_INFO_LOADING,
    GET_USER_INFO_SUCCESS,
    GET_USER_INFO_FAILURE,
    USER_LOGOUT,
};
